// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmVrGt5g1C8R8g96RQFtMaT6amY1wO5tQ',
    appId: '1:1024671615556:web:fc8f69d0202f430bd6ca11',
    messagingSenderId: '1024671615556',
    projectId: 'womanista-135a3',
    authDomain: 'womanista-135a3.firebaseapp.com',
    storageBucket: 'womanista-135a3.appspot.com',
    measurementId: 'G-FTRS8X5TKE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSb-Q15Y7R49ZTKYx18aeHSzpsKZF_m-E',
    appId: '1:1024671615556:android:223bac193970e53bd6ca11',
    messagingSenderId: '1024671615556',
    projectId: 'womanista-135a3',
    storageBucket: 'womanista-135a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLVEjkytI7cBAT0xouz5kwt8arnOffYzA',
    appId: '1:1024671615556:ios:4817215549ff338dd6ca11',
    messagingSenderId: '1024671615556',
    projectId: 'womanista-135a3',
    storageBucket: 'womanista-135a3.appspot.com',
    iosClientId: '1024671615556-35pbaqqvfapsak0uvsoshjvimjotoug3.apps.googleusercontent.com',
    iosBundleId: 'com.womanista',
  );
}
